"""add_workspace_context

Revision ID: 091e813eb7b2
Revises: 39755d0463c9
Create Date: 2026-04-14 13:10:46.100652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '091e813eb7b2'
down_revision: Union[str, None] = '39755d0463c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_context', sa.Column('context', sa.Text(), nullable=True))
    op.drop_column('workspace_context', 'notes')
    op.drop_column('workspace_context', 'focus_linear_team_ids')
    op.drop_column('workspace_context', 'team_name')
    op.drop_column('workspace_context', 'focus_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_context', sa.Column('focus_projects', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('workspace_context', sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspace_context', sa.Column('focus_linear_team_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('workspace_context', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('workspace_context', 'context')
    # ### end Alembic commands ###
