"""add_linear_teams

Revision ID: 1098c9508bea
Revises: 0001
Create Date: 2026-05-04 19:03:24.398462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1098c9508bea'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linear_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linear_team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linear_team_id')
    )
    op.add_column('runs', sa.Column('linear_team_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'linear_team_id')
    op.drop_table('linear_teams')
    # ### end Alembic commands ###
