"""add_feedback_events

Revision ID: ceafbb9fcebf
Revises: 091e813eb7b2
Create Date: 2026-04-15 21:54:34.291173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceafbb9fcebf'
down_revision: Union[str, None] = '091e813eb7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_events', sa.Column('category', sa.Text(), nullable=False))
    op.drop_column('feedback_events', 'taxonomy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_events', sa.Column('taxonomy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('feedback_events', 'category')
    # ### end Alembic commands ###
