"""add_feedback_events_with_embedding

Revision ID: dc6da573d16f
Revises: 091e813eb7b2
Create Date: 2026-04-21 20:45:22.753587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'dc6da573d16f'
down_revision: Union[str, None] = '091e813eb7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_events', sa.Column('category', sa.Text(), nullable=False))
    op.add_column('feedback_events', sa.Column('embedding', Vector(1536), nullable=True))
    op.drop_column('feedback_events', 'taxonomy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_events', sa.Column('taxonomy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('feedback_events', 'embedding')
    op.drop_column('feedback_events', 'category')
    # ### end Alembic commands ###
